// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings FFI gerados a partir de native/autogest.h
class AutogestBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  AutogestBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  AutogestBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  /// ==================================================================== *
  /// GRUPO 1 — DADOS   (src/dados.c)
  /// Preenchem e retornam uma struct. Nao validam — a validacao e feita
  /// antes, pelas funcoes do Grupo 2.
  /// ====================================================================
  Veiculo criar_veiculo(
    ffi.Pointer<ffi.Char> nome,
    ffi.Pointer<ffi.Char> placa,
    ffi.Pointer<ffi.Char> marca,
    ffi.Pointer<ffi.Char> modelo,
    int ano,
  ) {
    return _criar_veiculo(nome, placa, marca, modelo, ano);
  }

  late final _criar_veiculoPtr =
      _lookup<
        ffi.NativeFunction<
          Veiculo Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Int,
          )
        >
      >('criar_veiculo');
  late final _criar_veiculo = _criar_veiculoPtr
      .asFunction<
        Veiculo Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          int,
        )
      >();

  Abastecimento criar_abastecimento(
    int id,
    int data,
    double litros,
    double valor_total,
    double km,
    ffi.Pointer<ffi.Char> combustivel,
  ) {
    return _criar_abastecimento(id, data, litros, valor_total, km, combustivel);
  }

  late final _criar_abastecimentoPtr =
      _lookup<
        ffi.NativeFunction<
          Abastecimento Function(
            ffi.Int,
            ffi.Int64,
            ffi.Double,
            ffi.Double,
            ffi.Double,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('criar_abastecimento');
  late final _criar_abastecimento = _criar_abastecimentoPtr
      .asFunction<
        Abastecimento Function(
          int,
          int,
          double,
          double,
          double,
          ffi.Pointer<ffi.Char>,
        )
      >();

  Manutencao criar_manutencao(
    int id,
    TipoManutencao tipo,
    ffi.Pointer<ffi.Char> descricao,
    int data_realizada,
    double custo,
    int intervalo_dias,
  ) {
    return _criar_manutencao(
      id,
      tipo.value,
      descricao,
      data_realizada,
      custo,
      intervalo_dias,
    );
  }

  late final _criar_manutencaoPtr =
      _lookup<
        ffi.NativeFunction<
          Manutencao Function(
            ffi.Int,
            ffi.UnsignedInt,
            ffi.Pointer<ffi.Char>,
            ffi.Int64,
            ffi.Double,
            ffi.Int,
          )
        >
      >('criar_manutencao');
  late final _criar_manutencao = _criar_manutencaoPtr
      .asFunction<
        Manutencao Function(int, int, ffi.Pointer<ffi.Char>, int, double, int)
      >();

  /// ==================================================================== *
  /// GRUPO 2 — VALIDACAO   (src/validacao.c)
  /// Retornam int (CodigoErro): SUCESSO (0) ou um codigo negativo.
  /// ====================================================================
  int validar_km(double km_novo, double km_anterior) {
    return _validar_km(km_novo, km_anterior);
  }

  late final _validar_kmPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Double, ffi.Double)>>(
        'validar_km',
      );
  late final _validar_km = _validar_kmPtr
      .asFunction<int Function(double, double)>();

  int validar_data(int data) {
    return _validar_data(data);
  }

  late final _validar_dataPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int64)>>('validar_data');
  late final _validar_data = _validar_dataPtr.asFunction<int Function(int)>();

  int validar_valor(double valor) {
    return _validar_valor(valor);
  }

  late final _validar_valorPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Double)>>(
        'validar_valor',
      );
  late final _validar_valor = _validar_valorPtr
      .asFunction<int Function(double)>();

  int validar_litros(double litros) {
    return _validar_litros(litros);
  }

  late final _validar_litrosPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Double)>>(
        'validar_litros',
      );
  late final _validar_litros = _validar_litrosPtr
      .asFunction<int Function(double)>();

  int validar_intervalo_dias(int dias) {
    return _validar_intervalo_dias(dias);
  }

  late final _validar_intervalo_diasPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int)>>(
        'validar_intervalo_dias',
      );
  late final _validar_intervalo_dias = _validar_intervalo_diasPtr
      .asFunction<int Function(int)>();

  int validar_string(ffi.Pointer<ffi.Char> str) {
    return _validar_string(str);
  }

  late final _validar_stringPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>)>>(
        'validar_string',
      );
  late final _validar_string = _validar_stringPtr
      .asFunction<int Function(ffi.Pointer<ffi.Char>)>();

  int editar_veiculo(
    ffi.Pointer<Veiculo> v,
    ffi.Pointer<ffi.Char> campo,
    ffi.Pointer<ffi.Char> valor,
  ) {
    return _editar_veiculo(v, campo, valor);
  }

  late final _editar_veiculoPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<Veiculo>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('editar_veiculo');
  late final _editar_veiculo = _editar_veiculoPtr
      .asFunction<
        int Function(
          ffi.Pointer<Veiculo>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  int editar_abastecimento(
    ffi.Pointer<Abastecimento> a,
    ffi.Pointer<ffi.Char> campo,
    ffi.Pointer<ffi.Char> valor,
  ) {
    return _editar_abastecimento(a, campo, valor);
  }

  late final _editar_abastecimentoPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<Abastecimento>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('editar_abastecimento');
  late final _editar_abastecimento = _editar_abastecimentoPtr
      .asFunction<
        int Function(
          ffi.Pointer<Abastecimento>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  int editar_manutencao(
    ffi.Pointer<Manutencao> m,
    ffi.Pointer<ffi.Char> campo,
    ffi.Pointer<ffi.Char> valor,
  ) {
    return _editar_manutencao(m, campo, valor);
  }

  late final _editar_manutencaoPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<Manutencao>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('editar_manutencao');
  late final _editar_manutencao = _editar_manutencaoPtr
      .asFunction<
        int Function(
          ffi.Pointer<Manutencao>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  /// ==================================================================== *
  /// GRUPO 3 — CALCULOS   (src/calculos.c)
  /// Recebem vetores de registros (vindos do banco) e devolvem valores.
  /// ====================================================================
  double calcular_custo_por_km(
    ffi.Pointer<Abastecimento> lista,
    int total,
    double km_inicio,
    double km_fim,
  ) {
    return _calcular_custo_por_km(lista, total, km_inicio, km_fim);
  }

  late final _calcular_custo_por_kmPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Double Function(
            ffi.Pointer<Abastecimento>,
            ffi.Int,
            ffi.Double,
            ffi.Double,
          )
        >
      >('calcular_custo_por_km');
  late final _calcular_custo_por_km = _calcular_custo_por_kmPtr
      .asFunction<
        double Function(ffi.Pointer<Abastecimento>, int, double, double)
      >();

  double calcular_gasto_periodo(
    ffi.Pointer<Abastecimento> lista,
    int total,
    int inicio,
    int fim,
  ) {
    return _calcular_gasto_periodo(lista, total, inicio, fim);
  }

  late final _calcular_gasto_periodoPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Double Function(
            ffi.Pointer<Abastecimento>,
            ffi.Int,
            ffi.Int64,
            ffi.Int64,
          )
        >
      >('calcular_gasto_periodo');
  late final _calcular_gasto_periodo = _calcular_gasto_periodoPtr
      .asFunction<double Function(ffi.Pointer<Abastecimento>, int, int, int)>();

  double calcular_km_por_litro(
    double km_atual,
    double km_anterior,
    double litros,
  ) {
    return _calcular_km_por_litro(km_atual, km_anterior, litros);
  }

  late final _calcular_km_por_litroPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Double Function(ffi.Double, ffi.Double, ffi.Double)
        >
      >('calcular_km_por_litro');
  late final _calcular_km_por_litro = _calcular_km_por_litroPtr
      .asFunction<double Function(double, double, double)>();

  double obter_km_atual(ffi.Pointer<Abastecimento> lista, int total) {
    return _obter_km_atual(lista, total);
  }

  late final _obter_km_atualPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Double Function(ffi.Pointer<Abastecimento>, ffi.Int)
        >
      >('obter_km_atual');
  late final _obter_km_atual = _obter_km_atualPtr
      .asFunction<double Function(ffi.Pointer<Abastecimento>, int)>();

  double calcular_km_por_litro_geral(
    ffi.Pointer<Abastecimento> lista,
    int total,
  ) {
    return _calcular_km_por_litro_geral(lista, total);
  }

  late final _calcular_km_por_litro_geralPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Double Function(ffi.Pointer<Abastecimento>, ffi.Int)
        >
      >('calcular_km_por_litro_geral');
  late final _calcular_km_por_litro_geral = _calcular_km_por_litro_geralPtr
      .asFunction<double Function(ffi.Pointer<Abastecimento>, int)>();

  ResumoGastos calcular_resumo_gastos(
    ffi.Pointer<Abastecimento> abastecimentos,
    int total_abast,
    ffi.Pointer<Manutencao> manutencoes,
    int total_manut,
  ) {
    return _calcular_resumo_gastos(
      abastecimentos,
      total_abast,
      manutencoes,
      total_manut,
    );
  }

  late final _calcular_resumo_gastosPtr =
      _lookup<
        ffi.NativeFunction<
          ResumoGastos Function(
            ffi.Pointer<Abastecimento>,
            ffi.Int,
            ffi.Pointer<Manutencao>,
            ffi.Int,
          )
        >
      >('calcular_resumo_gastos');
  late final _calcular_resumo_gastos = _calcular_resumo_gastosPtr
      .asFunction<
        ResumoGastos Function(
          ffi.Pointer<Abastecimento>,
          int,
          ffi.Pointer<Manutencao>,
          int,
        )
      >();

  /// ==================================================================== *
  /// GRUPO 4 — MOTOR DE ALERTAS   (src/alertas.c)
  /// gerar_lista_alertas aloca com malloc; o chamador libera com
  /// liberar_lista_alertas (seguro chamar com NULL).
  /// ====================================================================
  int calcular_dias_restantes(
    int data_realizada,
    int intervalo_dias,
    int hoje,
  ) {
    return _calcular_dias_restantes(data_realizada, intervalo_dias, hoje);
  }

  late final _calcular_dias_restantesPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Int64, ffi.Int, ffi.Int64)>
      >('calcular_dias_restantes');
  late final _calcular_dias_restantes = _calcular_dias_restantesPtr
      .asFunction<int Function(int, int, int)>();

  StatusAlerta classificar_alerta(int dias_restantes, int janela_aviso) {
    return StatusAlerta.fromValue(
      _classificar_alerta(dias_restantes, janela_aviso),
    );
  }

  late final _classificar_alertaPtr =
      _lookup<ffi.NativeFunction<ffi.UnsignedInt Function(ffi.Int, ffi.Int)>>(
        'classificar_alerta',
      );
  late final _classificar_alerta = _classificar_alertaPtr
      .asFunction<int Function(int, int)>();

  ffi.Pointer<Alerta> gerar_lista_alertas(
    ffi.Pointer<Manutencao> manutencoes,
    int total_manut,
    int hoje,
    int janela_aviso,
    ffi.Pointer<ffi.Int> total_alertas,
  ) {
    return _gerar_lista_alertas(
      manutencoes,
      total_manut,
      hoje,
      janela_aviso,
      total_alertas,
    );
  }

  late final _gerar_lista_alertasPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<Alerta> Function(
            ffi.Pointer<Manutencao>,
            ffi.Int,
            ffi.Int64,
            ffi.Int,
            ffi.Pointer<ffi.Int>,
          )
        >
      >('gerar_lista_alertas');
  late final _gerar_lista_alertas = _gerar_lista_alertasPtr
      .asFunction<
        ffi.Pointer<Alerta> Function(
          ffi.Pointer<Manutencao>,
          int,
          int,
          int,
          ffi.Pointer<ffi.Int>,
        )
      >();

  void liberar_lista_alertas(ffi.Pointer<Alerta> lista) {
    return _liberar_lista_alertas(lista);
  }

  late final _liberar_lista_alertasPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<Alerta>)>>(
        'liberar_lista_alertas',
      );
  late final _liberar_lista_alertas = _liberar_lista_alertasPtr
      .asFunction<void Function(ffi.Pointer<Alerta>)>();
}

/// -------------------------------------------------------------------- *
/// ENUMS
/// --------------------------------------------------------------------
enum TipoManutencao {
  TROCA_OLEO(0),
  FILTRO_AR(1),
  FILTRO_COMBUSTIVEL(2),
  FILTRO_CABINE(3),
  PNEUS(4),
  CORREIA_DENTADA(5),
  ALINHAMENTO(6),
  BALANCEAMENTO(7),
  PASTILHA_FREIO(8),
  OUTROS(9),

  /// sentinela — vale como contagem
  TOTAL_TIPOS_MANUTENCAO(10);

  final int value;
  const TipoManutencao(this.value);

  static TipoManutencao fromValue(int value) => switch (value) {
    0 => TROCA_OLEO,
    1 => FILTRO_AR,
    2 => FILTRO_COMBUSTIVEL,
    3 => FILTRO_CABINE,
    4 => PNEUS,
    5 => CORREIA_DENTADA,
    6 => ALINHAMENTO,
    7 => BALANCEAMENTO,
    8 => PASTILHA_FREIO,
    9 => OUTROS,
    10 => TOTAL_TIPOS_MANUTENCAO,
    _ => throw ArgumentError("Unknown value for TipoManutencao: $value"),
  };
}

enum StatusAlerta {
  EM_DIA(0),
  PROXIMO(1),
  VENCIDO(2);

  final int value;
  const StatusAlerta(this.value);

  static StatusAlerta fromValue(int value) => switch (value) {
    0 => EM_DIA,
    1 => PROXIMO,
    2 => VENCIDO,
    _ => throw ArgumentError("Unknown value for StatusAlerta: $value"),
  };
}

enum CriterioAlerta {
  POR_TEMPO(0),
  POR_KM(1),
  POR_AMBOS(2);

  final int value;
  const CriterioAlerta(this.value);

  static CriterioAlerta fromValue(int value) => switch (value) {
    0 => POR_TEMPO,
    1 => POR_KM,
    2 => POR_AMBOS,
    _ => throw ArgumentError("Unknown value for CriterioAlerta: $value"),
  };
}

enum CodigoErro {
  SUCESSO(0),
  ERRO_KM_DECRESCENTE(-1),
  ERRO_VALOR_NEGATIVO(-2),
  ERRO_LITROS_NEGATIVO(-3),
  ERRO_DATA_INVALIDA(-4),
  ERRO_INTERVALO_INVALIDO(-5),
  ERRO_INDICE_INVALIDO(-6),
  ERRO_MEMORIA(-7),
  ERRO_CAMPO_VAZIO(-8);

  final int value;
  const CodigoErro(this.value);

  static CodigoErro fromValue(int value) => switch (value) {
    0 => SUCESSO,
    -1 => ERRO_KM_DECRESCENTE,
    -2 => ERRO_VALOR_NEGATIVO,
    -3 => ERRO_LITROS_NEGATIVO,
    -4 => ERRO_DATA_INVALIDA,
    -5 => ERRO_INTERVALO_INVALIDO,
    -6 => ERRO_INDICE_INVALIDO,
    -7 => ERRO_MEMORIA,
    -8 => ERRO_CAMPO_VAZIO,
    _ => throw ArgumentError("Unknown value for CodigoErro: $value"),
  };
}

/// -------------------------------------------------------------------- *
/// STRUCTS
/// --------------------------------------------------------------------
final class Veiculo extends ffi.Struct {
  @ffi.Array.multi([50])
  external ffi.Array<ffi.Char> nome;

  @ffi.Array.multi([9])
  external ffi.Array<ffi.Char> placa;

  @ffi.Array.multi([30])
  external ffi.Array<ffi.Char> marca;

  @ffi.Array.multi([30])
  external ffi.Array<ffi.Char> modelo;

  @ffi.Int()
  external int ano;
}

final class Abastecimento extends ffi.Struct {
  @ffi.Int()
  external int id;

  @ffi.Int64()
  external int data;

  @ffi.Double()
  external double litros;

  @ffi.Double()
  external double valor_total;

  @ffi.Double()
  external double km;

  @ffi.Array.multi([20])
  external ffi.Array<ffi.Char> combustivel;
}

final class Manutencao extends ffi.Struct {
  @ffi.Int()
  external int id;

  @ffi.UnsignedInt()
  external int tipoAsInt;

  TipoManutencao get tipo => TipoManutencao.fromValue(tipoAsInt);

  @ffi.Array.multi([100])
  external ffi.Array<ffi.Char> descricao;

  @ffi.Int64()
  external int data_realizada;

  @ffi.Double()
  external double custo;

  /// dormente — preenchido pelo km atual
  @ffi.Double()
  external double km_ultima;

  /// dormente — reservado para a Fase 2
  @ffi.Double()
  external double intervalo_km;

  @ffi.Int()
  external int intervalo_dias;

  /// Fase 1: sempre POR_TEMPO
  @ffi.UnsignedInt()
  external int criterioAsInt;

  CriterioAlerta get criterio => CriterioAlerta.fromValue(criterioAsInt);
}

final class Alerta extends ffi.Struct {
  @ffi.Int()
  external int id_manutencao;

  @ffi.UnsignedInt()
  external int tipoAsInt;

  TipoManutencao get tipo => TipoManutencao.fromValue(tipoAsInt);

  @ffi.UnsignedInt()
  external int statusAsInt;

  StatusAlerta get status => StatusAlerta.fromValue(statusAsInt);

  @ffi.Int()
  external int dias_restantes;

  @ffi.Int64()
  external int data_proxima;
}

final class ResumoGastos extends ffi.Struct {
  /// indice 0 = janeiro
  @ffi.Array.multi([12])
  external ffi.Array<ffi.Double> gasto_por_mes;

  /// indice = TipoManutencao
  @ffi.Array.multi([10])
  external ffi.Array<ffi.Double> gasto_por_categoria;

  @ffi.Double()
  external double total_abastecimentos;

  @ffi.Double()
  external double total_manutencoes;

  @ffi.Double()
  external double total_geral;

  @ffi.Array.multi([12, 11])
  external ffi.Array<ffi.Array<ffi.Double>> gasto_por_mes_categoria;
}

const int INT64_MAX = 9223372036854775807;

const int INT64_MIN = -9223372036854775808;

const int UINT64_MAX = -1;

const int __INT_LEAST64_MIN = -9223372036854775808;

const int __INT_LEAST64_MAX = 9223372036854775807;

const int __UINT_LEAST64_MAX = -1;

const int __INT_LEAST32_MIN = -2147483648;

const int __INT_LEAST32_MAX = 2147483647;

const int __UINT_LEAST32_MAX = 4294967295;

const int __INT_LEAST16_MIN = -32768;

const int __INT_LEAST16_MAX = 32767;

const int __UINT_LEAST16_MAX = 65535;

const int __INT_LEAST8_MIN = -128;

const int __INT_LEAST8_MAX = 127;

const int __UINT_LEAST8_MAX = 255;

const int INT_LEAST64_MIN = -9223372036854775808;

const int INT_LEAST64_MAX = 9223372036854775807;

const int UINT_LEAST64_MAX = -1;

const int INT_FAST64_MIN = -9223372036854775808;

const int INT_FAST64_MAX = 9223372036854775807;

const int UINT_FAST64_MAX = -1;

const int INT32_MAX = 2147483647;

const int INT32_MIN = -2147483648;

const int UINT32_MAX = 4294967295;

const int INT_LEAST32_MIN = -2147483648;

const int INT_LEAST32_MAX = 2147483647;

const int UINT_LEAST32_MAX = 4294967295;

const int INT_FAST32_MIN = -2147483648;

const int INT_FAST32_MAX = 2147483647;

const int UINT_FAST32_MAX = 4294967295;

const int INT16_MAX = 32767;

const int INT16_MIN = -32768;

const int UINT16_MAX = 65535;

const int INT_LEAST16_MIN = -32768;

const int INT_LEAST16_MAX = 32767;

const int UINT_LEAST16_MAX = 65535;

const int INT_FAST16_MIN = -32768;

const int INT_FAST16_MAX = 32767;

const int UINT_FAST16_MAX = 65535;

const int INT8_MAX = 127;

const int INT8_MIN = -128;

const int UINT8_MAX = 255;

const int INT_LEAST8_MIN = -128;

const int INT_LEAST8_MAX = 127;

const int UINT_LEAST8_MAX = 255;

const int INT_FAST8_MIN = -128;

const int INT_FAST8_MAX = 127;

const int UINT_FAST8_MAX = 255;

const int INTPTR_MIN = -9223372036854775808;

const int INTPTR_MAX = 9223372036854775807;

const int UINTPTR_MAX = -1;

const int PTRDIFF_MIN = -9223372036854775808;

const int PTRDIFF_MAX = 9223372036854775807;

const int SIZE_MAX = -1;

const int INTMAX_MIN = -9223372036854775808;

const int INTMAX_MAX = 9223372036854775807;

const int UINTMAX_MAX = -1;

const int SIG_ATOMIC_MIN = -2147483648;

const int SIG_ATOMIC_MAX = 2147483647;

const int WINT_MIN = 0;

const int WINT_MAX = 65535;

const int WCHAR_MAX = 65535;

const int WCHAR_MIN = 0;

const int MAX_NOME = 50;

const int MAX_PLACA = 9;

const int MAX_MARCA = 30;

const int MAX_MODELO = 30;

const int MAX_COMBUSTIVEL = 20;

const int MAX_DESCRICAO = 100;

const int JANELA_AVISO_PADRAO = 30;

const int CATEGORIA_COMBUSTIVEL = 0;

const int TOTAL_CATEGORIAS_GASTO = 11;
